# Generated by Django 4.0.3 on 2022-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock',
            field=models.CharField(max_length=30),
        ),
    ]
